# spring
spring:
  application:
    name:hust-cycling-club-back-end
  jackson:
    generator:
      write-numbers-as-strings: true
  servlet:
    multipart:
      max-file-size: 5MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///hust-cycling
      username: root
      password: 123456
      drive-class-name: com.mysql.cj.jdbc.Driver

# server
server:
  port: 8080
  servlet:
    context-path: /api

# mybatis-plus
mybatis-plus:
  type-aliases-package: com.lcd.atlcd.dao.entity
  global-config:
    db-config:
      logic-delete-field: isDeleted
      id-type: auto
    configuration:
      map-underscore-to-camel-case: true

#jwt
jwt:
  token:
    tokenExpiration: 120
    tokenSignKey: hustcyclingclubhustcyclingclubhustcyclingclubhustcyclingclubhustcyclingclubhustcyclingclubhustcyclingclubhustcyclingclub

# 项目配置
hust-cycling-club:
  # 跨域配置
  cors:
    # 允许跨域的域名
    allow-origins:
      - http://localhost:3000
      - http://localhost:8080